ISS-22784: React Native iOS PIP View
100mslive/100ms-react-native pull request #1400
Opened 2024-07-01 12:13 UTC by ygit

# Description

- ISS-22784: React Native iOS PIP View

### Pre-launch Checklist

- [x] The [Documentation] is updated accordingly, or this PR doesn't require it.
- [x] I have updated the `ExampleAppChangelog.txt` file with relevant changes.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making, or this PR is test-exempt.
- [x] All existing and new tests are passing.

[Documentation]: https://www.100ms.live/docs

2024-07-04 15:13 UTC, stanwolverine commented on packages/react-native-hms/ios/HMSRNSDK.swift
> +
I think we can delete this code block

2024-07-04 15:57 UTC, stanwolverine requested changes
I noticed that HMSIOSPIPController code is still there, please confirm and remove it if we are not using

2024-07-09 07:53 UTC, ygit commented on packages/react-native-hms/ios/HMSRNSDK.swift
> +
Done

2024-07-09 09:37 UTC, stanwolverine approved these changes
LGTM

2024-07-09 09:37 UTC, merged